### ISSUE TITLE
Video output not works

### ISSUE THREAD

**Issue by manelDev** [matrix-io/malos-eye#18]
Hi there,

When i start the demos from malos_eye (gesture and demographic demos) all works, but i can't see the video output, everything is configured in the js files and I enabled SPI and Camera on Raspi-Config and I got installed de bcm2835 library but not works anyway.

Any idea about this?

Thanks.

**Comment by manelDev** [comment]
when I'm trying to start `./malos_eye` show me this error:
You can query specific driver info using port 22012
terminate called after throwing an instance of 'zmq::error_t'
  what(): Address already in use
Aborted

How can i fix this?

**Comment by manelDev** [comment]
when I'm trying to start `./malos_eye` show me this error:
You can query specific driver info using port 22012
Registered driver GESTURE with port 22013
Invalid configuration for GESTURE driver

any about this?

**Comment by arhuaco** [comment]
The video output is not shown. I didn't see this before, sorry.

**Comment by magdesign** [comment]
Is there any chance to get a live video output with realtime demographics as seen in this picture:
https://apps.matrix.one/#!/apps/demographictest

Thanks for any inputs.
