### ISSUE TITLE
Package repository doesn't work

### ISSUE THREAD

**Issue by MarioFux** [matrix-io/malos-eye#19]
Unfortunately I get this error for malos-eye:
Err:4 http://packages.matrix.one/matrix-creator ./ Release
404 Not Found [IP: 172.217.16.144 80]
Reading package lists... Done
E: The repository 'http://packages.matrix.one/matrix-creator ./ Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by lucasmoraisdev** [comment]
ok @MarioFux so can you provide me the steps you did until this error?

**Comment by MarioFux** [comment]
I followed to instructions in the README.md:
# Base repository and assoc. packages
echo "deb http://packages.matrix.one/matrix-creator/ ./" | sudo tee --append /etc/apt/sources.list
sudo apt-get update
=> then the error above.

**Comment by lucasmoraisdev** [comment]
hmmm, i've just tested here too and it worked fine. You can see it here: 
```
# pi @ raspberrypi in ~ [14:51:54] 
$ sudo apt-get update
Ign http://packages.matrix.one ./ InRelease                                                                                                   
Hit http://mirrordirector.raspbian.org jessie InRelease                                                                                       
Ign http://packages.matrix.one ./ Release.gpg  
Hit http://archive.raspberrypi.org jessie InRelease
Ign http://packages.matrix.one ./ Release                               
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages                             
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages                                                               
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages                                            
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages                                                 
Hit http://archive.raspberrypi.org jessie/main armhf Packages                                                    
Hit http://archive.raspberrypi.org jessie/ui armhf Packages                                
Hit http://packages.matrix.one ./ Packages                                                                                             
Ign http://packages.matrix.one ./ Translation-en_GB                                                              
Ign http://packages.matrix.one ./ Translation-en                                                                 
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB                                          
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB                               
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en     
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB     
Ign http://archive.raspberrypi.org jessie/main Translation-en            
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB 
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB           
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB      
Ign http://archive.raspberrypi.org jessie/ui Translation-en              
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done 
```
Do you mind showing me your sources.list ?

**Comment by MarioFux** [comment]
deb http://ftp.ch.debian.org/debian/ stretch main non-free contrib
#deb http://ftp.ch.debian.org/debian/ sid main non-free contrib
deb-src http://ftp.ch.debian.org/debian/ stretch main non-free contrib

deb http://security.debian.org/debian-security stretch/updates main contrib non-free
deb-src http://security.debian.org/debian-security stretch/updates main contrib non-free
deb http://packages.matrix.one/matrix-creator/ ./

Not much in it. But I continue to "debug" the problem myself. Need to leave this place soon and thus won't be online for some hours.

**Comment by lucasmoraisdev** [comment]
hmm ok, if you have any updates from this you can comment here when you get online again. I will keep looking here for what can be done

**Comment by arhuaco** [comment]
Can we close this issue @MarioFux . Wondering if things worked for you.
