### ISSUE TITLE
Examples work, but Raspberry Pi crashes and becomes unresponsive 

### ISSUE THREAD

**Issue by luisnomad** [matrix-io/malos-eye#5]
I have been able to run the examples, after installing a camera (not provided). It somehow works, but after detecting my face for a few seconds, the Raspberry crashes badly and there's no other way to get it back to work other than pulling the AC cable, which I think it's not the best way.

Also, I noticed that installing malos makes the Raspberry struggle and totally unstable, crashing often for no reason, or making ssh really really slow... Any ideas?

I know it's all beta and all, but it'd be good to inform of these things, so we know what to expect. When I see the videos and the advertisement, it all looks like it just works, and that it's reliable. It seems that's not the case at all.

**Comment by brianofrokk3r** [comment]
Hey @luisnomad,

Thank you for the feedback, it's very much appreciated. We actually haven't experienced these issues when running on our test devices here. Right now we can see the average CPU load of `malos_eye` is `~40%` when active. Tested on a Raspberry Pi 3, we don't have any sort of device or system crash. 

Can you provide us with a list of processes that are currently running on your device? In the meantime we'll investigate further here.

![screen shot 2017-01-23 at 2 34 55 pm](https://cloud.githubusercontent.com/assets/113014/22219553/30f56914-e179-11e6-8f28-d0b2f6da396b.png)

Please provide us more system information so we can assist.

**Comment by brianofrokk3r** [comment]
@luisnomad please provide OS information as well.
