### ISSUE TITLE
MALOS eye not passing image buffer through protos. Expect image buffer for extraction at later stages.

### ISSUE THREAD

**Issue by brianofrokk3r** [matrix-io/malos-eye#7]
MALOS eye not passing image buffer through protos. Expect image buffer for extraction at later stages. Please advise @arhuaco.

**Comment by arhuaco** [comment]
A new version of MALOS eye will be release next week, the one that contains face descriptors. This version can have the image buffer for each detection, no issues with this.

**Comment by brianofrokk3r** [comment]
@arhuaco when face descriptors are complete please close this.

**Comment by arhuaco** [comment]
This has been done for a while. Today we'll upload the package for internal testing and then for release.
